version: '3.4'

volumes:
  sanic.db.volume:
    name: sanic.db.volume

services:
  web:
    build: "./web"
    container_name: sanic.web
    command: /bin/sh -c "python /code/project/main.py"
    ports:
      - "8000:8000"
    volumes:
      - "./web/project/app:/code/project/app"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sanic.db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sanicpass
      TZ: "Asia/Tokyo"
    volumes:
      - sanic.db.volume:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - "./mysql:/etc/mysql/conf.d"
